name: Bicep CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bicep
        run: az bicep install

      - name: Run Bicep Build
        run: az bicep build --file main.bicep
